// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdRATn-0Eq_oBzibgzC2S3rWOClpiN5OA',
    appId: '1:865792435843:web:d6f820db8d1f7f839addb6',
    messagingSenderId: '865792435843',
    projectId: 'voice-control-smart-home',
    authDomain: 'voice-control-smart-home.firebaseapp.com',
    storageBucket: 'voice-control-smart-home.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1x0mh01cF1PaRf-7-E0RIz8AIDb-W4eg',
    appId: '1:865792435843:android:22f438fbc67140eb9addb6',
    messagingSenderId: '865792435843',
    projectId: 'voice-control-smart-home',
    storageBucket: 'voice-control-smart-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN-MnV7h4SY1egQKFItQzsZAkVbNJXavY',
    appId: '1:865792435843:ios:7877bc0d6f3c09579addb6',
    messagingSenderId: '865792435843',
    projectId: 'voice-control-smart-home',
    storageBucket: 'voice-control-smart-home.firebasestorage.app',
    iosBundleId: 'com.example.voicecontrolsmarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN-MnV7h4SY1egQKFItQzsZAkVbNJXavY',
    appId: '1:865792435843:ios:7877bc0d6f3c09579addb6',
    messagingSenderId: '865792435843',
    projectId: 'voice-control-smart-home',
    storageBucket: 'voice-control-smart-home.firebasestorage.app',
    iosBundleId: 'com.example.voicecontrolsmarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdRATn-0Eq_oBzibgzC2S3rWOClpiN5OA',
    appId: '1:865792435843:web:50e8898bbf26b3349addb6',
    messagingSenderId: '865792435843',
    projectId: 'voice-control-smart-home',
    authDomain: 'voice-control-smart-home.firebaseapp.com',
    storageBucket: 'voice-control-smart-home.firebasestorage.app',
  );

}